### ISSUE TITLE
blocky blurred area in demo

### ISSUE THREAD

**Issue by lif314** [Totoro97/f2-nerf#41]
In the demo video you gave, I found that there will be blocky blurred areas in some frames. This problem was even more pronounced when testing on my own dataset collected outdoors. What could be the reason for this? Thank you so much for your work!

<img width="593" alt="image" src="https://github.com/Totoro97/f2-nerf/assets/63114150/70b5a597-7f50-429a-96de-0818ae56db2a">

On my datasets:

https://github.com/Totoro97/f2-nerf/assets/63114150/f753dd47-01b2-4516-ac80-2d46aee3fa23

**Comment by Totoro97** [comment]
Hi, thanks for your interest in this project! The empty gray regions are octree nodes that are not visible to the training cameras, so they are automatically removed.

The video results look weird. I will first check if it is due to inaccurate camera poses. By the way, what is the split setting of training/testing sets?

**Comment by JIANG-CX** [comment]
> > Hi, thanks for your interest in this project! The empty gray regions are octree nodes that are not visible to the training cameras, so they are automatically removed.
> > The video results look weird. I will first check if it is due to inaccurate camera poses. By the way, what is the split setting of training/testing sets?
> 
> I used the default settings, `wanjinyou.yaml` and `wanjinyou_big.yaml`.

Hi. I find the same phenomenon. How do you deal with this issue?
