### ISSUE TITLE
Can you provide a requirments.txt file or any other thing to clarify the dependencies

### ISSUE THREAD

**Issue by anan-dad** [Totoro97/f2-nerf#49]
thanks

**Comment by yuedajiong** [comment]
here you are, any thanks to me?

!!! make sure your GPU support half-precision float, otherwise ...  


wget https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run
sh cuda_11.7.0_515.43.04_linux.run
export PATH=$PATH:/usr/local/cuda-11.7/bin
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.7/lib64
nvcc -V 

apt-get install cmake
apt-get install zlib1g-dev
apt-get install libpthread-stubs0-dev

apt-get install intel-mkl-64bit-2020.2
source /opt/intel/compilers_and_libraries_2020/linux/mkl/bin/mklvars.sh intel64 ilp64

cd External
wget https://download.pytorch.org/libtorch/cu117/libtorch-cxx11-abi-shared-with-deps-1.13.1%2Bcu117.zip
unzip libtorch-cxx11-abi-shared-with-deps-1.13.1+cu117.zip
cd ..

cmake . -B build    # -D TCNN_CUDA_ARCHITECTURES=86 -D CMAKE_CUDA_COMPILER=$(which nvcc) 
cmake --build build --target main --config RelWithDebInfo -j

pip install hydra-core --upgrade

**Comment by anan-dad** [comment]
> here you are, any thanks to me?
> 
> !!! make sure your GPU support half-precision float, otherwise ...
> 
> wget https://developer.download.nvidia.com/compute/cuda/11.7.0/local_installers/cuda_11.7.0_515.43.04_linux.run sh cuda_11.7.0_515.43.04_linux.run export PATH=$PATH:/usr/local/cuda-11.7/bin export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda-11.7/lib64 nvcc -V
> 
> apt-get install cmake apt-get install zlib1g-dev apt-get install libpthread-stubs0-dev
> 
> apt-get install intel-mkl-64bit-2020.2 source /opt/intel/compilers_and_libraries_2020/linux/mkl/bin/mklvars.sh intel64 ilp64
> 
> cd External wget https://download.pytorch.org/libtorch/cu117/libtorch-cxx11-abi-shared-with-deps-1.13.1%2Bcu117.zip unzip libtorch-cxx11-abi-shared-with-deps-1.13.1+cu117.zip cd ..
> 
> cmake . -B build # -D TCNN_CUDA_ARCHITECTURES=86 -D CMAKE_CUDA_COMPILER=$(which nvcc) cmake --build build --target main --config RelWithDebInfo -j
> 
> pip install hydra-core --upgrade

You rock!!! Let me have a quick try and get back to you!

**Comment by anan-dad** [comment]
@yuedajiong Thank you! Tested okay!

And for anyone wants to follow the author's setup guide, just pip install these 4 packages before running the example:

`$ pip install click`
`$ pip install numpy`
`$ pip install OmegaConf`
`$ pip install hydra-core`

**Comment by yuedajiong** [comment]
@anan-dad     hi, bro.   I am trying to design a powerful implicit representation 3d reconstruction e2e differentalble network.   Yes, NeRF is the most important reference.   and I need:   P0: camera-free,   P1-a: faster(train/reconstruction and infer/render),  P1-b: dynamic object/scene,    P2:  generate by referenc-object as condition, eg.   generate hair and head/face/ears as reference obj.    P3: a few images(eg, hair, 3+ around 1+top frames; dog:  1/top ~ video: walking)        and finally, I hope the algorithm shold be:    rgb = f(xyz, timestep), that means:   give timestep, we can generate a walking dog.

as we known, most of these topics are still openning.   no good solution, especial gen by ref-obj.

it looks you are familar with this NeRF direction,  any guidance are welcome. ...

**Comment by anan-dad** [comment]
@yuedajiong you're right, there is no mature solution yet, but nerf is an exiting area wth new approaches coming out everyday! I'll try to reply to you after you give me more details:

P0, P2: camera-free means generate rgb = f(xyz, timestep) on reference image?
P3: I didn't get the inputs, any more details?
